# -*- coding: utf-8 -*-
"""OCR_Tesseract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/aannddrree/disciplinaIA/blob/main/OCR_Tesseract.ipynb
"""

!sudo apt-get install tesseract-ocr
!pip install pytesseract
!sudo apt-get install -y tesseract-ocr-por

!tesseract --list-langs

# Importar bibliotecas necessárias
import pytesseract
from PIL import Image
import requests
from io import BytesIO

# imagem de exemplo
img = '/content/sample_data/4c294f7444cafa78001fc6c67cd31767.jpg'

# Executar OCR na imagem
texto = pytesseract.image_to_string(img, lang='por')

# Exibir o texto extraído
print(texto)